import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import lucideCollection from '@iconify-json/lucide/icons.json';
import {
  addTemplate,
  addVitePlugin,
  defineNuxtModule,
  resolveFiles,
  updateTemplates,
  useLogger,
} from '@nuxt/kit';

type LucideIcon = {
  body?: string;
  width?: number;
  height?: number;
  parent?: string;
};

type LucideCollection = {
  icons: Record<string, LucideIcon>;
  aliases: Record<string, LucideIcon>;
};

type ResolvedGuideIcon = {
  body: string;
  width?: number;
  height?: number;
};

const FALLBACK_ICON = 'circle-question-mark';
const ICON_MARKER = /<!--\s*i:(i-lucide-[\w.-]+)\s*-->/gi;
const ROOT_GUIDES = ['API.md', 'FAQ.md', 'NEWS.md', 'README.md'];

const resolveIcon = (name: string): ResolvedGuideIcon | null => {
  const collection = lucideCollection as LucideCollection;
  let currentName: string | undefined = name;
  const visited = new Set<string>();

  while (currentName && !visited.has(currentName)) {
    visited.add(currentName);

    const icon: LucideIcon | undefined =
      collection.icons[currentName] ?? collection.aliases[currentName];
    if (!icon) {
      return null;
    }

    if (icon.body) {
      return {
        body: icon.body,
        ...(icon.width ? { width: icon.width } : {}),
        ...(icon.height ? { height: icon.height } : {}),
      };
    }

    currentName = icon.parent;
  }

  return null;
};

export default defineNuxtModule({
  meta: {
    name: 'watchstate-guide-icons',
  },
  setup(_options, nuxt) {
    const repositoryRoot = resolve(nuxt.options.rootDir, '..');
    const guidesDirectory = resolve(repositoryRoot, 'guides');
    const rootGuideFiles = ROOT_GUIDES.map((file) => resolve(repositoryRoot, file));
    const template = addTemplate({
      filename: 'guide-icons.ts',
      write: true,
      async getContents() {
        const guideFiles = await resolveFiles(guidesDirectory, '**/*.md');
        const files = [...rootGuideFiles, ...guideFiles];
        const usages = new Map<string, Set<string>>();

        for (const file of files) {
          const markdown = await readFile(file, 'utf8');
          for (const match of markdown.matchAll(ICON_MARKER)) {
            const marker = match[1];
            if (!marker) {
              continue;
            }

            const name = marker.replace(/^i-lucide-/, '');
            const paths = usages.get(name) ?? new Set<string>();
            paths.add(file.replace(`${repositoryRoot}/`, ''));
            usages.set(name, paths);
          }
        }

        usages.set(FALLBACK_ICON, usages.get(FALLBACK_ICON) ?? new Set<string>());

        const icons: Record<string, ResolvedGuideIcon> = {};
        for (const [name, paths] of [...usages.entries()].sort(([left], [right]) =>
          left.localeCompare(right),
        )) {
          const icon = resolveIcon(name);
          if (!icon) {
            throw new Error(
              `Unknown Lucide guide icon '${name}' referenced by ${[...paths].sort().join(', ')}`,
            );
          }

          icons[name] = icon;
        }

        return [
          '// Generated by modules/guide-icons.ts. Do not edit.',
          'export type GuideIcon = {',
          '  body: string',
          '  width?: number',
          '  height?: number',
          '}',
          `export const guideIcons: Record<string, GuideIcon> = ${JSON.stringify(icons, null, 2)}`,
          '',
        ].join('\n');
      },
    });

    if (false === nuxt.options.dev) {
      return;
    }

    const logger = useLogger('guide-icons');
    addVitePlugin({
      name: 'watchstate-guide-icons-hmr',
      configureServer(server) {
        let updateTimer: ReturnType<typeof setTimeout> | undefined;

        const isServedGuide = (path: string): boolean => {
          const absolutePath = resolve(path);
          return (
            rootGuideFiles.includes(absolutePath) ||
            (absolutePath.endsWith('.md') && absolutePath.startsWith(`${guidesDirectory}/`))
          );
        };

        const regenerate = async (): Promise<void> => {
          try {
            await updateTemplates({ filter: (candidate) => candidate.dst === template.dst });

            const modules = server.environments.client.moduleGraph.getModulesByFile(template.dst);
            if (!modules) {
              return;
            }

            await Promise.all(
              [...modules].map((module) => server.environments.client.reloadModule(module)),
            );
          } catch (error) {
            logger.error(error);
          }
        };

        const scheduleUpdate = (path: string): void => {
          if (!isServedGuide(path)) {
            return;
          }

          if (updateTimer) {
            clearTimeout(updateTimer);
          }
          updateTimer = setTimeout(() => void regenerate(), 50);
        };

        server.watcher.add([guidesDirectory, ...rootGuideFiles]);
        server.watcher.on('add', scheduleUpdate);
        server.watcher.on('change', scheduleUpdate);
        server.watcher.on('unlink', scheduleUpdate);
        server.httpServer?.once('close', () => {
          if (updateTimer) {
            clearTimeout(updateTimer);
          }
          server.watcher.off('add', scheduleUpdate);
          server.watcher.off('change', scheduleUpdate);
          server.watcher.off('unlink', scheduleUpdate);
        });
      },
    });
  },
});
