tz: Asia/Kuwait
logger:
  stderr:
    level: INFO
  file:
    enabled: true
    type: stream
    level: ERROR
    filename: '%(path)%(DS)logs%(DS)app.log'
  syslog:
    enabled: false
    type: syslog
    level: INFO
