<?php

declare(strict_types=1);

namespace App\Migration;

use arabcoders\database\Attributes\Migration;
use arabcoders\database\Connection;
use arabcoders\database\Schema\Blueprint\Blueprint;
use arabcoders\database\Schema\Blueprint\TableBlueprint;
use arabcoders\database\Schema\Definition\ColumnType;
use arabcoders\database\Schema\Migration\SchemaBlueprintMigration;

#[Migration(id: '260720140746', name: 'media_health')]
final class Migration_260720140746 extends SchemaBlueprintMigration
{
    public function __invoke(Connection $runner, Blueprint $blueprint): void
    {
        $blueprint->useMigrationPlan(\arabcoders\database\Schema\Migration\SchemaMigrationPlan::fromArray([
            'from' => ['tables' => []],
            'to' => [
                'tables' => [
                    [
                        'name' => 'media_health_reports',
                        'engine' => [],
                        'charset' => [],
                        'collation' => [],
                        'previousName' => null,
                        'sourceClass' => 'App\\Models\\MediaHealthReport',
                        'primaryKey' => ['id'],
                        'columns' => [
                            [
                                'name' => 'id',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => true,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'id',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'status',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'status',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'generated_at',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'generated_at',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'completed_at',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => true,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'completed_at',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'version',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => 1,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'version',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'state_count',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => 0,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'state_count',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'backend_count',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => 0,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'backend_count',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'summary',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => '{}',
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'summary',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'error',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => true,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'error',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                        ],
                        'indexes' => [
                            [
                                'name' => 'media_health_reports_status',
                                'columns' => ['status'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_reports_generated_at',
                                'columns' => ['generated_at'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                        ],
                        'foreignKeys' => [],
                    ],
                    [
                        'name' => 'media_health_report_items',
                        'engine' => [],
                        'charset' => [],
                        'collation' => [],
                        'previousName' => null,
                        'sourceClass' => 'App\\Models\\MediaHealthReportItem',
                        'primaryKey' => ['id'],
                        'columns' => [
                            [
                                'name' => 'id',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => true,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'id',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'report_id',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'report_id',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'state_id',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'state_id',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'type',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'type',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'title',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'title',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'year',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => true,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'year',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'season',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => true,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'season',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'episode',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => true,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'episode',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'status',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'status',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'severity',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'severity',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'confidence',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'confidence',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'backend_count',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'backend_count',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'expected_backend_count',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'expected_backend_count',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'reasons',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => '[]',
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'reasons',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'signals',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => '{}',
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'signals',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                        ],
                        'indexes' => [
                            [
                                'name' => 'media_health_report_items_report_id',
                                'columns' => ['report_id'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_report_items_state_id',
                                'columns' => ['state_id'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_report_items_type',
                                'columns' => ['type'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_report_items_title',
                                'columns' => ['title'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_report_items_status',
                                'columns' => ['status'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_report_items_severity',
                                'columns' => ['severity'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                        ],
                        'foreignKeys' => [],
                    ],
                ],
            ],
            'operations' => [
                [
                    'type' => 'create_table',
                    'table' => [
                        'name' => 'media_health_reports',
                        'engine' => [],
                        'charset' => [],
                        'collation' => [],
                        'previousName' => null,
                        'sourceClass' => 'App\\Models\\MediaHealthReport',
                        'primaryKey' => ['id'],
                        'columns' => [
                            [
                                'name' => 'id',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => true,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'id',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'status',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'status',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'generated_at',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'generated_at',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'completed_at',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => true,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'completed_at',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'version',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => 1,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'version',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'state_count',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => 0,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'state_count',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'backend_count',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => 0,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'backend_count',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'summary',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => '{}',
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'summary',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'error',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => true,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'error',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                        ],
                        'indexes' => [
                            [
                                'name' => 'media_health_reports_status',
                                'columns' => ['status'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_reports_generated_at',
                                'columns' => ['generated_at'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                        ],
                        'foreignKeys' => [],
                    ],
                ],
                [
                    'type' => 'add_index',
                    'table' => 'media_health_reports',
                    'index' => [
                        'name' => 'media_health_reports_status',
                        'columns' => ['status'],
                        'unique' => false,
                        'type' => 'index',
                        'algorithm' => [],
                        'lengths' => [],
                        'where' => null,
                        'expression' => null,
                    ],
                ],
                [
                    'type' => 'add_index',
                    'table' => 'media_health_reports',
                    'index' => [
                        'name' => 'media_health_reports_generated_at',
                        'columns' => ['generated_at'],
                        'unique' => false,
                        'type' => 'index',
                        'algorithm' => [],
                        'lengths' => [],
                        'where' => null,
                        'expression' => null,
                    ],
                ],
                [
                    'type' => 'create_table',
                    'table' => [
                        'name' => 'media_health_report_items',
                        'engine' => [],
                        'charset' => [],
                        'collation' => [],
                        'previousName' => null,
                        'sourceClass' => 'App\\Models\\MediaHealthReportItem',
                        'primaryKey' => ['id'],
                        'columns' => [
                            [
                                'name' => 'id',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => true,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'id',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'report_id',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'report_id',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'state_id',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'state_id',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'type',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'type',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'title',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'title',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'year',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => true,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'year',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'season',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => true,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'season',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'episode',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => true,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'episode',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'status',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'status',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'severity',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'severity',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'confidence',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'confidence',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'backend_count',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'backend_count',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'expected_backend_count',
                                'type' => 'int',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => false,
                                'default' => null,
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'expected_backend_count',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'reasons',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => '[]',
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'reasons',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                            [
                                'name' => 'signals',
                                'type' => 'text',
                                'typeName' => null,
                                'length' => null,
                                'precision' => null,
                                'scale' => null,
                                'unsigned' => false,
                                'nullable' => false,
                                'autoIncrement' => false,
                                'hasDefault' => true,
                                'default' => '{}',
                                'defaultIsExpression' => false,
                                'charset' => [],
                                'collation' => [],
                                'comment' => null,
                                'onUpdate' => null,
                                'previousName' => null,
                                'propertyName' => 'signals',
                                'allowed' => null,
                                'check' => false,
                                'checkExpression' => null,
                                'generated' => false,
                                'generatedExpression' => null,
                                'generatedStored' => null,
                            ],
                        ],
                        'indexes' => [
                            [
                                'name' => 'media_health_report_items_report_id',
                                'columns' => ['report_id'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_report_items_state_id',
                                'columns' => ['state_id'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_report_items_type',
                                'columns' => ['type'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_report_items_title',
                                'columns' => ['title'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_report_items_status',
                                'columns' => ['status'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                            [
                                'name' => 'media_health_report_items_severity',
                                'columns' => ['severity'],
                                'unique' => false,
                                'type' => 'index',
                                'algorithm' => [],
                                'lengths' => [],
                                'where' => null,
                                'expression' => null,
                            ],
                        ],
                        'foreignKeys' => [],
                    ],
                ],
                [
                    'type' => 'add_index',
                    'table' => 'media_health_report_items',
                    'index' => [
                        'name' => 'media_health_report_items_report_id',
                        'columns' => ['report_id'],
                        'unique' => false,
                        'type' => 'index',
                        'algorithm' => [],
                        'lengths' => [],
                        'where' => null,
                        'expression' => null,
                    ],
                ],
                [
                    'type' => 'add_index',
                    'table' => 'media_health_report_items',
                    'index' => [
                        'name' => 'media_health_report_items_state_id',
                        'columns' => ['state_id'],
                        'unique' => false,
                        'type' => 'index',
                        'algorithm' => [],
                        'lengths' => [],
                        'where' => null,
                        'expression' => null,
                    ],
                ],
                [
                    'type' => 'add_index',
                    'table' => 'media_health_report_items',
                    'index' => [
                        'name' => 'media_health_report_items_type',
                        'columns' => ['type'],
                        'unique' => false,
                        'type' => 'index',
                        'algorithm' => [],
                        'lengths' => [],
                        'where' => null,
                        'expression' => null,
                    ],
                ],
                [
                    'type' => 'add_index',
                    'table' => 'media_health_report_items',
                    'index' => [
                        'name' => 'media_health_report_items_title',
                        'columns' => ['title'],
                        'unique' => false,
                        'type' => 'index',
                        'algorithm' => [],
                        'lengths' => [],
                        'where' => null,
                        'expression' => null,
                    ],
                ],
                [
                    'type' => 'add_index',
                    'table' => 'media_health_report_items',
                    'index' => [
                        'name' => 'media_health_report_items_status',
                        'columns' => ['status'],
                        'unique' => false,
                        'type' => 'index',
                        'algorithm' => [],
                        'lengths' => [],
                        'where' => null,
                        'expression' => null,
                    ],
                ],
                [
                    'type' => 'add_index',
                    'table' => 'media_health_report_items',
                    'index' => [
                        'name' => 'media_health_report_items_severity',
                        'columns' => ['severity'],
                        'unique' => false,
                        'type' => 'index',
                        'algorithm' => [],
                        'lengths' => [],
                        'where' => null,
                        'expression' => null,
                    ],
                ],
            ],
        ]));
        $blueprint->createTable('media_health_reports', static function (TableBlueprint $table): void {
            $table->column('id', ColumnType::Int)->primary()->autoIncrement();
            $table->column('status', ColumnType::Text);
            $table->column('generated_at', ColumnType::Int);
            $table->column('completed_at', ColumnType::Int)->nullable();
            $table->column('version', ColumnType::Int)->default(1);
            $table->column('state_count', ColumnType::Int)->default(0);
            $table->column('backend_count', ColumnType::Int)->default(0);
            $table->column('summary', ColumnType::Text)->default('{}');
            $table->column('error', ColumnType::Text)->nullable();
            $table->index('status', 'media_health_reports_status');
            $table->index('generated_at', 'media_health_reports_generated_at');
        });
        $blueprint->createTable('media_health_report_items', static function (TableBlueprint $table): void {
            $table->column('id', ColumnType::Int)->primary()->autoIncrement();
            $table->column('report_id', ColumnType::Int);
            $table->column('state_id', ColumnType::Int);
            $table->column('type', ColumnType::Text);
            $table->column('title', ColumnType::Text);
            $table->column('year', ColumnType::Int)->nullable();
            $table->column('season', ColumnType::Int)->nullable();
            $table->column('episode', ColumnType::Int)->nullable();
            $table->column('status', ColumnType::Text);
            $table->column('severity', ColumnType::Int);
            $table->column('confidence', ColumnType::Int);
            $table->column('backend_count', ColumnType::Int);
            $table->column('expected_backend_count', ColumnType::Int);
            $table->column('reasons', ColumnType::Text)->default('[]');
            $table->column('signals', ColumnType::Text)->default('{}');
            $table->index('report_id', 'media_health_report_items_report_id');
            $table->index('state_id', 'media_health_report_items_state_id');
            $table->index('type', 'media_health_report_items_type');
            $table->index('title', 'media_health_report_items_title');
            $table->index('status', 'media_health_report_items_status');
            $table->index('severity', 'media_health_report_items_severity');
        });
    }
}
