name: Build Container Images

on:
  push:
    branches:
      - 'master'
      - 'dev'
    tags:
      - 'v*'

jobs:
  publish_docker_images:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: arabcoders/watchstate
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=raw,value=dev-latest,enable=${{ endsWith(github.ref, '/dev') }}
            type=ref,event=tag,enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          flavor: |
            latest=false
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
